spring:
  application:
    name: zubaobei-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
            - id: v1                     #网关路由到网易官网
              uri: lb://ZUBAOBEI-EUREKA-SERVER-INVOKER
              predicates:
                - Path=/v1/**
              filters:
                      - StripPrefix=1
server:
  port: 8000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
feign:
  hystrix:
    enabled: true
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG